admin dev readme
research-software-directory/research-software-directory pull request #537
Opened 2020-10-20 11:43 UTC by jspaaks

Refs #349

2020-10-21 11:49 UTC, jspaaks commented
Doing some more work on this, converted back to draft

2020-10-26 13:13 UTC, jspaaks commented
Hi @sverhoeven I feel this PR is a step in the right direction but it's not there yet. Could you give me some pointers?

2020-11-02 10:57 UTC, sverhoeven requested changes
I was hoping for something simpler. 

For example using docker-compose to start the required services on local ports defined in package.json:proxy. See https://github.com/research-software-directory/research-software-directory/pull/610 for simpler to dev experience, though slightly more complex setup.

2020-11-02 10:57 UTC, sverhoeven commented on admin/README.md
> +1.  Start the admin service in a development server: `yarn start`. It will tell you where to go to check the `admin`
To login in to admin interface you need to set the callback to `http://localhost:8000/auth/get_jwt` on https://github.com/settings/developers

2020-11-02 10:57 UTC, sverhoeven commented on admin/README.md
> +1.  Install yarn, `npm install -g yarn` (Note: there exists a similarly named package, Apache Hadoop YARN --please ignore
This is more a prereq, please move to prerequisite chapter.

2020-11-09 10:40 UTC, jspaaks commented
Hi @sverhoeven, thanks for the review. I still have to try out #610, but from scrolling through the diff it seems that is a better way to go than this PR. Shall I just mark this one as closed?

2020-11-10 14:23 UTC, sverhoeven commented
Let's close this one. And I will directly merge https://github.com/research-software-directory/research-software-directory/pull/610 to master.

2020-11-10 15:54 UTC, jspaaks commented
:+1:

2020-11-10 15:54 UTC, closed without merging