added link to ignore list so we can have meaningful ci again
research-software-directory/research-software-directory pull request #691
Opened 2020-11-25 14:00 UTC by jspaaks

# Pull request details

## List of related issues or pull requests

Refs: #ISSUE_NUMBER

## Describe the changes made in this pull request

## Instructions to review the pull request

2020-11-25 16:39 UTC, jspaaks commented
Probably good idea to assign someone at the standup, other PRs can benefit from this one.

2020-11-26 11:43 UTC, sverhoeven requested changes
Why are you linking to documents in tags? 

I would instead of ignoring it point to the document in the master branch. Using the following link
```
https://github.com/research-software-directory/research-software-directory/blob/master/docs/dev.md#verifying-the-local-installation
```

2020-11-26 11:47 UTC, jspaaks commented
I'm doing that because the link (in CHANGELOG) is describing the change from 2.x to 3.0.0 specifically, and I don't want it to become invalid over time as master develops beyond 3.0.0

2020-11-26 11:50 UTC, sverhoeven approved these changes
Ah OK, did not see link in CHANGELOG only in ./data-migration/2.x-to-3.x/README.md and ./data-migration/2.x-to-3.x/README.md . 

Agree that dev.md can change making the link kaput.

2020-11-26 11:52 UTC, jspaaks commented
Thanks for reviewing, let's see how green the other PRs really are ;)

2020-11-26 11:52 UTC, merged